# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US
tone_instructions: 'Be concise and actionable. Focus on code quality, security, and performance.'
early_access: true
enable_free_tier: true
inheritance: true
reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_instructions: ''
  high_level_summary_placeholder: '@coderabbitai summary'
  high_level_summary_in_walkthrough: false
  auto_title_placeholder: '@coderabbitai'
  auto_title_instructions: ''
  review_status: true
  commit_status: true
  fail_commit_status: true
  collapse_walkthrough: true
  changed_files_summary: true
  sequence_diagrams: true
  estimate_code_review_effort: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  labeling_instructions:
    - label: "bug"
      instructions: "Apply when the PR fixes a bug or addresses an error"
    - label: "game/rendering"
      instructions: "Apply when changes affect 3D rendering, Three.js, or R3F components"
    - label: "game/gameplay"
      instructions: "Apply when changes affect game mechanics, player movement, or controls"
    - label: "game/maze"
      instructions: "Apply when changes affect maze generation or navigation"
    - label: "game/audio"
      instructions: "Apply when changes affect audio systems or sound effects"
    - label: "game/horror"
      instructions: "Apply when changes affect horror effects, sanity, or atmosphere"
    - label: "ci/cd"
      instructions: "Apply when changes affect GitHub Actions, deployment, or build scripts"
    - label: "synthesis"
      instructions: "Apply when changes affect documentation, tests, or code quality"
  auto_apply_labels: true
  suggested_reviewers: true
  auto_assign_reviewers: true
  in_progress_fortune: true
  poem: true
  enable_prompt_for_ai_agents: true
  path_filters: []
  path_instructions:
    - path: "client/src/components/game/**"
      instructions: |
        This is a React Three Fiber game component. Check for:
        - Performance issues (avoid creating new objects in render loop)
        - Proper use of useFrame for animations
        - Memory leaks (dispose textures/geometries)
        - Correct use of refs vs state for animation values
        - Suspense boundaries for async resources
    - path: "client/src/game/**"
      instructions: |
        Game logic and state management. Check for:
        - Zustand store best practices
        - Pure functions where possible
        - Deterministic behavior for seeded randomness
    - path: "e2e/**"
      instructions: |
        Playwright E2E tests. ENFORCE docs/TESTING_STANDARDS.md:
        - REJECT any use of waitForTimeout - use condition-based waits
        - Use role-based selectors over test IDs
        - Tests must have meaningful assertions, not just screenshots
        - Proper test isolation
    - path: "**/*.test.tsx"
      instructions: |
        Unit tests. ENFORCE docs/TESTING_STANDARDS.md:
        - REJECT "renders without crashing" as the only test
        - R3F components MUST use @react-three/test-renderer
        - Tests must verify actual behavior, not just existence
        - Coverage requirements: Pure functions 90%, Components 80%, Store 95%
    - path: "**/*.test.ts"
      instructions: |
        Unit tests. ENFORCE docs/TESTING_STANDARDS.md:
        - Pure functions must have 90%+ coverage
        - Test edge cases and boundary conditions
        - Store actions must test state transitions
    - path: ".github/workflows/**"
      instructions: |
        GitHub Actions workflows. Check for:
        - Pinned action versions (SHA preferred)
        - Proper secret handling
        - Efficient caching strategies
  abort_on_close: true
  disable_cache: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - "WIP"
      - "[skip ci]"
      - "[skip review]"
    labels: []
    drafts: true  # Review draft PRs too
    base_branches:
      - main
    ignore_usernames: []
  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true
  pre_merge_checks:
    docstrings:
      mode: warning
      threshold: 60  # Reasonable threshold for game code
    title:
      mode: warning
      requirements: 'Use conventional commit format (feat:, fix:, docs:, chore:, refactor:, test:)'
    description:
      mode: warning
    issue_assessment:
      mode: warning
    custom_checks:
      - name: "Security Check"
        mode: "warning"
        instructions: |
          Verify no hardcoded secrets, API keys, or credentials.
          Check for common security issues (XSS, injection, etc.).
      - name: "R3F Performance Check"
        mode: "warning"
        instructions: |
          For R3F components, verify no object creation in render loops.
          Check for proper memoization and useCallback usage.
          Ensure textures/geometries are properly disposed.
  tools:
    ast-grep:
      rule_dirs: []
      util_dirs: []
      essential_rules: true
      packages: []
    shellcheck:
      enabled: true
    ruff:
      enabled: true
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      enabled_rules: []
      disabled_rules: []
      enabled_categories: []
      disabled_categories: []
      enabled_only: false
      level: default
    biome:
      enabled: true
    hadolint:
      enabled: true
    swiftlint:
      enabled: true
    phpstan:
      enabled: true
      level: default
    phpmd:
      enabled: true
    phpcs:
      enabled: true
    golangci-lint:
      enabled: true
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    detekt:
      enabled: true
    eslint:
      enabled: true
    flake8:
      enabled: true
    fortitudeLint:
      enabled: true
    rubocop:
      enabled: true
    buf:
      enabled: true
    regal:
      enabled: true
    actionlint:
      enabled: true
    pmd:
      enabled: true
    clang:
      enabled: true
    cppcheck:
      enabled: true
    semgrep:
      enabled: true
    circleci:
      enabled: true
    clippy:
      enabled: true
    sqlfluff:
      enabled: true
    prismaLint:
      enabled: true
    pylint:
      enabled: true
    oxc:
      enabled: true
    shopifyThemeCheck:
      enabled: true
    luacheck:
      enabled: true
    brakeman:
      enabled: true
    dotenvLint:
      enabled: true
    htmlhint:
      enabled: true
    checkmake:
      enabled: true
    osvScanner:
      enabled: true
chat:
  art: true
  auto_reply: true
  integrations:
    jira:
      usage: auto
    linear:
      usage: auto
knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns:
      - "CLAUDE.md"
      - "docs/ARCHITECTURE.md"
      - "docs/STYLE_GUIDE.md"
      - "docs/VISION.md"
      - "docs/TESTING_STANDARDS.md"
      - "docs/TESTING_ENHANCEMENTS.md"
  learnings:
    scope: global  # Share learnings across organization
  issues:
    scope: auto
  jira:
    usage: auto
    project_keys: []
  linear:
    usage: auto
    team_keys: []
  pull_requests:
    scope: auto
  mcp:
    usage: auto
    disabled_servers: []
code_generation:
  docstrings:
    language: en-US
    path_instructions:
      - path: "client/src/**"
        instructions: "Use JSDoc format with @param, @returns, and @example where helpful"
  unit_tests:
    path_instructions:
      - path: "client/src/components/game/**"
        instructions: |
          MANDATORY: Follow docs/TESTING_STANDARDS.md
          - Use @react-three/test-renderer for R3F components
          - Test mesh props, events, and scene graph
          - NO "renders without crashing" padding tests
          - Minimum 70% coverage for R3F components
      - path: "client/src/components/**"
        instructions: |
          MANDATORY: Follow docs/TESTING_STANDARDS.md
          - Use Vitest + React Testing Library
          - Test actual behavior, not just rendering
          - Minimum 80% coverage
      - path: "client/src/game/**"
        instructions: |
          MANDATORY: Follow docs/TESTING_STANDARDS.md
          - Test pure functions with 90%+ coverage
          - Test all edge cases and boundary conditions
          - Store actions must test state transitions
          - Minimum 95% coverage for store
issue_enrichment:
  auto_enrich:
    enabled: true
  planning:
    enabled: true
    auto_planning:
      enabled: true
      labels:
        - "synthesis"     # Auto-plan synthesis issues
        - "bug"           # Auto-plan bug fixes
        - "critical"      # Auto-plan critical issues
        - "game/gameplay" # Auto-plan gameplay issues
        - "game/rendering" # Auto-plan rendering issues
        - "game/maze"     # Auto-plan maze issues
  labeling:
    labeling_instructions:
      - label: "bug"
        title: "Bug"
        description: "Issues describing unexpected behavior, errors, or regressions."
        instructions: "Apply when issue describes unexpected behavior or errors."
        when_to_apply:
          - "Issue reports broken functionality, crashes, or incorrect output."
          - "Logs or repro steps indicate a defect."
      - label: "critical"
        title: "Critical"
        description: "Issues requiring immediate attention due to severe impact or blocking risk."
        instructions: "Apply when issue is severe, blocking, or demands immediate attention."
        when_to_apply:
          - "Issue blocks core gameplay or causes data loss/security risk."
          - "Severity is high and needs expedited triage."
      - label: "game/rendering"
        title: "Rendering"
        description: "Issues related to 3D graphics, WebGL, or visual effects."
        instructions: "Apply when issue relates to 3D graphics, WebGL, or visual effects."
        when_to_apply:
          - "Issue involves shaders, post-processing, lighting, or R3F rendering."
          - "Visual artifacts or performance regressions tied to rendering."
      - label: "game/gameplay"
        title: "Gameplay"
        description: "Issues related to game mechanics or player experience."
        instructions: "Apply when issue relates to game mechanics or player experience."
        when_to_apply:
          - "Issue affects movement, controls, or progression."
          - "Gameplay systems behave unexpectedly."
      - label: "game/maze"
        title: "Maze"
        description: "Issues related to maze generation or navigation."
        instructions: "Apply when issue relates to maze generation or navigation."
        when_to_apply:
          - "Issue affects maze layout, traversal, or navigation logic."
          - "Pathfinding or node connectivity problems."
      - label: "synthesis"
        title: "Synthesis"
        description: "Issues that need AI-assisted planning or implementation."
        instructions: "Apply when issue needs AI-assisted planning or implementation."
        when_to_apply:
          - "Issue requests a plan or multi-step implementation guidance."
          - "Needs design synthesis across multiple files."
      - label: "queue-review"
        title: "Queue Review"
        description: "Issues that need human review before proceeding."
        instructions: "Apply when issue needs human review before proceeding."
        when_to_apply:
          - "Issue requires stakeholder decision or confirmation."
          - "Risky or ambiguous change needing approval."
    auto_apply_labels: true
